
spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411  #zipkin server的地址
  application:
    name: compute-service
  profiles:
    active: dev
server:
  port: 2222
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
logging:
  path: ../log/
  file: service.log
  level:
    com:
      scnu:
        service: DEBUG
